name: abm_trust
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - mesa=2.2.4
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - seaborn>=0.12.0
  - matplotlib>=3.6.0
  - pip